# Generated by Django 5.1.15 on 2026-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                ("title", models.TextField(verbose_name="název")),
                ("authors", models.TextField(blank=True, verbose_name="autoři")),
                (
                    "journal",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="časopis"
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="rok"
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True, db_index=True, max_length=120, verbose_name="DOI"
                    ),
                ),
                (
                    "pmid",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, verbose_name="PMID"
                    ),
                ),
                ("abstract", models.TextField(blank=True, verbose_name="abstrakt")),
                (
                    "url",
                    models.URLField(blank=True, max_length=500, verbose_name="odkaz"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Navrženo (čeká na schválení)"),
                            ("approved", "Zařazeno"),
                            ("rejected", "Zamítnuto"),
                        ],
                        default="suggested",
                        max_length=12,
                        verbose_name="stav",
                    ),
                ),
                (
                    "evidence_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("meta", "Metaanalýza / systematický přehled"),
                            ("rct", "Randomizovaná kontrolovaná studie"),
                            ("cohort", "Kohortová studie"),
                            ("cross", "Průřezová studie"),
                            ("case", "Kazuistika / série"),
                            ("expert", "Expertní stanovisko"),
                        ],
                        max_length=10,
                        verbose_name="úroveň evidence",
                    ),
                ),
                (
                    "population_sport",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="populace – sport"
                    ),
                ),
                (
                    "population_sex",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Ženy"), ("M", "Muži"), ("B", "Obě")],
                        max_length=1,
                        verbose_name="populace – pohlaví",
                    ),
                ),
                (
                    "population_age_min",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="populace – věk od"
                    ),
                ),
                (
                    "population_age_max",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="populace – věk do"
                    ),
                ),
                (
                    "population_level",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="populace – úroveň"
                    ),
                ),
                (
                    "sample_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="velikost vzorku"
                    ),
                ),
                (
                    "curator_note",
                    models.TextField(
                        blank=True,
                        help_text="K čemu je studie relevantní, jaká má omezení.",
                        verbose_name="anotace kurátora",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="štítky"),
                ),
            ],
            options={
                "verbose_name": "článek",
                "verbose_name_plural": "články",
                "ordering": ["-year", "title"],
            },
        ),
    ]
