# Generated by Django 5.1.15 on 2026-10-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_vlastni_pristroje"),
        ("evidence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="key_finding",
            field=models.TextField(
                blank=True,
                help_text="1–3 věty: co studie zjistila a co to znamená pro testování nebo trénink. Tohle dostane jazykový model, když článek cituje.",
                verbose_name="hlavní zjištění pro praxi",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="limitations",
            field=models.TextField(
                blank=True,
                help_text="Na co si dát pozor: malý vzorek, jiná populace, jen korelace…",
                verbose_name="omezení",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="metrics",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="catalog.metricdef",
                verbose_name="ukazatele",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="protocols",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="catalog.protocol",
                verbose_name="testy",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="curator_note",
            field=models.TextField(
                blank=True,
                help_text="Pro laboratoř; model ji dostane, jen když chybí hlavní zjištění.",
                verbose_name="interní poznámka kurátora",
            ),
        ),
    ]
