# Generated by Django 5.1.15 on 2026-10-08 12:03

import re

from django.db import migrations, models


def text_to_sports(apps, schema_editor):
    """„tenis“, „fotbal, ragby“ → sporty z katalogu; co se nenajde, zůstane jako text."""
    Article = apps.get_model("evidence", "Article")
    Sport = apps.get_model("subjects", "Sport")
    sports = {s.name.casefold(): s for s in Sport.objects.all()}
    for article in Article.objects.exclude(population_sport=""):
        rest = []
        for part in re.split(r"\s*[,;/]\s*|\s+a\s+", article.population_sport):
            if not part.strip():
                continue
            sport = sports.get(part.strip().casefold())
            if sport is not None:
                article.sports.add(sport)
            else:
                rest.append(part.strip())
        article.population_sport = ", ".join(rest)
        article.save(update_fields=["population_sport"])


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0002_zjisteni_omezeni_temata"),
        ("subjects", "0006_datum_narozeni"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="sports",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ve kterých sportech studie vznikla.",
                related_name="articles",
                to="subjects.sport",
                verbose_name="sporty",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="population_sport",
            field=models.CharField(
                blank=True,
                help_text="Sport, který v katalogu není (např. baseball).",
                max_length=120,
                verbose_name="jiný sport",
            ),
        ),
        migrations.RunPython(text_to_sports, migrations.RunPython.noop),
    ]
