# Generated by Django 5.1.15 on 2026-10-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0003_sporty_clanku"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="ai_draft",
            field=models.JSONField(blank=True, null=True, verbose_name="návrh od AI"),
        ),
        migrations.AddField(
            model_name="article",
            name="ai_writing_model",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="návrh píše model"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="ai_writing_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="návrh se začal psát"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="pdf",
            field=models.FileField(
                blank=True, upload_to="clanky/", verbose_name="PDF článku"
            ),
        ),
    ]
