# Generated by Django 5.1.15 on 2026-10-08 15:07

import apps.evidence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0004_pdf_a_navrh_ai"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pdf",
            field=models.FileField(
                blank=True,
                max_length=255,
                upload_to=apps.evidence.models.pdf_path,
                verbose_name="PDF článku",
            ),
        ),
    ]
