# Generated by Django 5.1.15 on 2026-09-21 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("core", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtocolRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Např. {"teplota": 21, "rozcvicka_min": 10}',
                        verbose_name="podmínky",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="poznámka")),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="catalog.protocol",
                        verbose_name="protokol",
                    ),
                ),
            ],
            options={
                "verbose_name": "provedení protokolu",
                "verbose_name_plural": "provedení protokolů",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RawFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "file",
                    models.FileField(upload_to="raw/%Y/%m/", verbose_name="soubor"),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="původní název"),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Zabrání dvojímu importu téhož souboru.",
                        max_length=64,
                        verbose_name="otisk obsahu (SHA-256)",
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="přístroj"
                    ),
                ),
                (
                    "format",
                    models.CharField(blank=True, max_length=40, verbose_name="formát"),
                ),
                (
                    "size_bytes",
                    models.BigIntegerField(default=0, verbose_name="velikost"),
                ),
                (
                    "protocol_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_files",
                        to="measurements.protocolrun",
                        verbose_name="provedení protokolu",
                    ),
                ),
            ],
            options={
                "verbose_name": "zdrojový soubor",
                "verbose_name_plural": "zdrojové soubory",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                ("date", models.DateField(db_index=True, verbose_name="datum")),
                (
                    "location",
                    models.CharField(blank=True, max_length=120, verbose_name="místo"),
                ),
                (
                    "season_phase",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prep", "Přípravné období"),
                            ("comp", "Závodní období"),
                            ("trans", "Přechodné období"),
                            ("rtp", "Návrat po zranění"),
                            ("", "Neuvedeno"),
                        ],
                        max_length=10,
                        verbose_name="fáze sezóny",
                    ),
                ),
                (
                    "fatigue_rating",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="subjektivní únava (1–10)"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="poznámka")),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="operátor",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="subjects.subject",
                        verbose_name="sportovec",
                    ),
                ),
            ],
            options={
                "verbose_name": "testovací den",
                "verbose_name_plural": "testovací dny",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="protocolrun",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocol_runs",
                to="measurements.testsession",
                verbose_name="testovací den",
            ),
        ),
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="pořadí pokusu"),
                ),
                ("is_valid", models.BooleanField(default=True, verbose_name="platný")),
                (
                    "invalid_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="důvod neplatnosti"
                    ),
                ),
                (
                    "protocol_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trials",
                        to="measurements.protocolrun",
                        verbose_name="provedení protokolu",
                    ),
                ),
            ],
            options={
                "verbose_name": "pokus",
                "verbose_name_plural": "pokusy",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("L", "Levá"),
                            ("R", "Pravá"),
                            ("B", "Oboustranně"),
                            ("D", "Dominantní"),
                            ("N", "Nedominantní"),
                        ],
                        max_length=1,
                        verbose_name="strana",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("con", "Koncentricky"),
                            ("ecc", "Excentricky"),
                            ("iso", "Izometricky"),
                            ("", "Neurčeno"),
                        ],
                        max_length=3,
                        verbose_name="režim",
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        blank=True, null=True, verbose_name="rychlost (°/s)"
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        blank=True,
                        help_text="Např. paže, trup, noha – u segmentálních metod.",
                        max_length=32,
                        verbose_name="segment",
                    ),
                ),
                ("value", models.FloatField(verbose_name="hodnota")),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("ok", "V pořádku"),
                            ("suspect", "Podezřelá hodnota"),
                            ("range", "Mimo věrohodný rozsah"),
                            ("manual", "Ručně upraveno"),
                        ],
                        default="ok",
                        max_length=10,
                        verbose_name="kvalita",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="poznámka"
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurements",
                        to="catalog.metricdef",
                        verbose_name="metrika",
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="measurements.trial",
                        verbose_name="pokus",
                    ),
                ),
            ],
            options={
                "verbose_name": "měření",
                "verbose_name_plural": "měření",
            },
        ),
        migrations.AddIndex(
            model_name="testsession",
            index=models.Index(
                fields=["subject", "-date"], name="measurement_subject_e2a9df_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="trial",
            constraint=models.UniqueConstraint(
                fields=("protocol_run", "number"), name="uniq_trial_number"
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["metric", "side", "mode", "speed"],
                name="measurement_metric__7fa60a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["trial", "metric"], name="measurement_trial_i_6ea766_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="measurement",
            constraint=models.UniqueConstraint(
                fields=("trial", "metric", "side", "mode", "speed", "segment"),
                name="uniq_measurement_qualifiers",
            ),
        ),
    ]
