# Generated by Django 5.1.15 on 2026-09-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="protocolrun",
            options={
                "ordering": ["started_at", "created_at"],
                "verbose_name": "provedení protokolu",
                "verbose_name_plural": "provedení protokolů",
            },
        ),
        migrations.AddField(
            model_name="protocolrun",
            name="external_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Např. ID testu z VALD. Díky ní opakovaný import téhož testu nic nezdvojí, jen aktualizuje hodnoty.",
                max_length=200,
                verbose_name="identifikace ve zdroji",
            ),
        ),
        migrations.AddField(
            model_name="protocolrun",
            name="is_primary",
            field=models.BooleanField(
                default=True,
                help_text="Z hlavního provedení se berou hodnoty dne do trendů, pravidel a srovnání. Opakovaná měření téhož dne se ukazují zvlášť.",
                verbose_name="hlavní měření dne",
            ),
        ),
        migrations.AddField(
            model_name="protocolrun",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="čas testu"),
        ),
    ]
