# Generated by Django 5.1.15 on 2026-09-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_terenni_testy_a_dotazniky"),
        ("measurements", "0002_opakovana_mereni_a_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsession",
            name="humidity_pct",
            field=models.FloatField(blank=True, null=True, verbose_name="vlhkost (%)"),
        ),
        migrations.AddField(
            model_name="testsession",
            name="temperature_c",
            field=models.FloatField(blank=True, null=True, verbose_name="teplota (°C)"),
        ),
        migrations.CreateModel(
            name="QuestionnaireResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("operator", "Zadal operátor"),
                            ("sportovec", "Vyplnil sportovec"),
                        ],
                        default="operator",
                        max_length=10,
                        verbose_name="kdo vyplnil",
                    ),
                ),
                (
                    "protocol_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="measurements.protocolrun",
                        verbose_name="po testu",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="catalog.questionnaire",
                        verbose_name="dotazník",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="measurements.testsession",
                        verbose_name="testovací den",
                    ),
                ),
            ],
            options={
                "verbose_name": "vyplněný dotazník",
                "verbose_name_plural": "vyplněné dotazníky",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.FloatField(blank=True, null=True, verbose_name="hodnota"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="catalog.question",
                        verbose_name="otázka",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="measurements.questionnaireresponse",
                        verbose_name="vyplněný dotazník",
                    ),
                ),
            ],
            options={
                "verbose_name": "odpověď",
                "verbose_name_plural": "odpovědi",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("response", "question"), name="uniq_answer"
                    )
                ],
            },
        ),
    ]
