# Generated by Django 5.1.15 on 2026-09-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="název")),
                ("code", models.SlugField(max_length=32, verbose_name="kód")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
            ],
            options={
                "verbose_name": "sport",
                "verbose_name_plural": "sporty",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Pseudonym, např. FTVS-0001. Nikdy neobsahuje jméno.",
                        max_length=32,
                        verbose_name="kód",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("F", "Žena"),
                            ("M", "Muž"),
                            ("X", "Jiné / neuvedeno"),
                        ],
                        default="X",
                        max_length=1,
                        verbose_name="pohlaví",
                    ),
                ),
                (
                    "birth_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Jen rok – přesné datum není potřeba.",
                        null=True,
                        verbose_name="rok narození",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("rec", "Rekreační"),
                            ("trained", "Trénovaný"),
                            ("national", "Národní úroveň"),
                            ("intl", "Mezinárodní úroveň"),
                        ],
                        default="trained",
                        max_length=20,
                        verbose_name="úroveň",
                    ),
                ),
                (
                    "dominant_side",
                    models.CharField(
                        blank=True,
                        choices=[("L", "Levá"), ("R", "Pravá")],
                        max_length=1,
                        verbose_name="dominantní strana",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="aktivní"),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Provozní poznámka. Nikdy diagnózy ani zdravotní údaje.",
                        verbose_name="poznámka",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subjects",
                        to="subjects.sport",
                        verbose_name="sport",
                    ),
                ),
            ],
            options={
                "verbose_name": "sportovec",
                "verbose_name_plural": "sportovci",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("testing", "Funkční testování"),
                            ("longitudinal", "Opakované měření a sledování v čase"),
                            (
                                "handover",
                                "Předání zprávy poskytovateli zdravotních služeb",
                            ),
                            (
                                "research",
                                "Sekundární použití pro výzkum (anonymizovaně)",
                            ),
                            ("genetics", "Genetická data"),
                            ("microbiome", "Mikrobiom"),
                        ],
                        max_length=20,
                        verbose_name="rozsah",
                    ),
                ),
                ("granted_on", models.DateField(verbose_name="uděleno")),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="platnost do"),
                ),
                (
                    "revoked_on",
                    models.DateField(blank=True, null=True, verbose_name="odvoláno"),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        upload_to="consents/",
                        verbose_name="podepsaný dokument",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="poznámka"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="subjects.subject",
                        verbose_name="sportovec",
                    ),
                ),
            ],
            options={
                "verbose_name": "souhlas",
                "verbose_name_plural": "souhlasy",
                "ordering": ["-granted_on"],
            },
        ),
        migrations.CreateModel(
            name="SubjectIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "first_name_enc",
                    models.TextField(blank=True, verbose_name="jméno (šifrovaně)"),
                ),
                (
                    "last_name_enc",
                    models.TextField(blank=True, verbose_name="příjmení (šifrovaně)"),
                ),
                (
                    "email_enc",
                    models.TextField(blank=True, verbose_name="e-mail (šifrovaně)"),
                ),
                (
                    "phone_enc",
                    models.TextField(blank=True, verbose_name="telefon (šifrovaně)"),
                ),
                (
                    "last_name_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Umožňuje přesné vyhledání bez dešifrování.",
                        max_length=64,
                        verbose_name="hash příjmení",
                    ),
                ),
                (
                    "subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity",
                        to="subjects.subject",
                        verbose_name="sportovec",
                    ),
                ),
            ],
            options={
                "verbose_name": "identita sportovce",
                "verbose_name_plural": "identity sportovců",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="název")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teams",
                        to="subjects.sport",
                        verbose_name="sport",
                    ),
                ),
            ],
            options={
                "verbose_name": "tým",
                "verbose_name_plural": "týmy",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="subjects.team",
                verbose_name="tým",
            ),
        ),
        migrations.AddConstraint(
            model_name="sport",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="uniq_sport_code_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="uniq_subject_code_per_org"
            ),
        ),
    ]
