# Generated by Django 5.1.15 on 2026-09-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="source_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash identifikačních údajů ze zdrojového souboru. Umožňuje opakovaný import téže osoby, aniž by se kamkoli ukládalo jméno.",
                max_length=64,
                verbose_name="klíč zdroje",
            ),
        ),
    ]
