# Generated by Django 5.1.15 on 2026-09-25 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_subject_source_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectExternalId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("vald", "VALD – ID sportovce"),
                            ("extid", "VALD – ExtId"),
                            ("hash_jmeno_narozeni", "Jméno a datum narození (hash)"),
                            ("hash_jmeno", "Jméno (hash)"),
                        ],
                        max_length=32,
                        verbose_name="systém",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="hodnota"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_ids",
                        to="subjects.subject",
                        verbose_name="sportovec",
                    ),
                ),
            ],
            options={
                "verbose_name": "identifikátor v jiném systému",
                "verbose_name_plural": "identifikátory v jiných systémech",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subject", "system", "value"),
                        name="uniq_subject_external_id",
                    )
                ],
            },
        ),
    ]
