# Generated by Django 5.1.15 on 2026-09-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0003_identifikatory_v_jinych_systemech"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Věková nebo výkonnostní kategorie, např. „dorost“. Podle ní se vybírá baterie testů.",
                max_length=60,
                verbose_name="kategorie",
            ),
        ),
    ]
