# Generated by Django 5.1.15 on 2026-10-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0004_kategorie_sportovce"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectexternalid",
            name="system",
            field=models.CharField(
                choices=[
                    ("vald", "VALD – ID sportovce"),
                    ("extid", "VALD – ExtId"),
                    ("pristroj", "ID v jiném přístroji"),
                    ("hash_jmeno_narozeni", "Jméno a datum narození (hash)"),
                    ("hash_jmeno", "Jméno (hash)"),
                ],
                max_length=32,
                verbose_name="systém",
            ),
        ),
    ]
