# Generated by Django 5.1.15 on 2026-10-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0005_id_v_pristroji"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectidentity",
            name="birth_date_enc",
            field=models.TextField(
                blank=True, verbose_name="datum narození (šifrovaně)"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="birth_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Jen rok. Přesné datum je šifrovaně v identitě sportovce.",
                null=True,
                verbose_name="rok narození",
            ),
        ),
    ]
