# Generated by Django 5.1.15 on 2026-09-30 18:10

import apps.booking.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0007_terenni_testy_a_dotazniky"),
        ("core", "0001_initial"),
        ("measurements", "0003_prostredi_a_dotazniky"),
        ("subjects", "0004_kategorie_sportovce"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("balicek", "Balíček"), ("test", "Jednotlivý test")],
                        default="test",
                        max_length=10,
                        verbose_name="druh",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="název")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="popis pro klienta"),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0, verbose_name="cena za osobu (Kč)"
                    ),
                ),
                (
                    "duration_min",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="orientační délka (min)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="pořadí"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="nabízet"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
                (
                    "protocols",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Které testy se po schválení založí.",
                        related_name="offers",
                        to="catalog.protocol",
                        verbose_name="testy",
                    ),
                ),
            ],
            options={
                "verbose_name": "položka nabídky",
                "verbose_name_plural": "nabídka testování",
                "ordering": ["kind", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("jednotlivec", "Jednotlivec"),
                            ("tym", "Tým / skupina"),
                        ],
                        default="jednotlivec",
                        max_length=12,
                        verbose_name="kdo žádá",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("overeni", "Čeká na potvrzení e-mailu"),
                            ("nova", "Nová – ke schválení"),
                            ("schvalena", "Schválená"),
                            ("zamitnuta", "Zamítnutá"),
                        ],
                        db_index=True,
                        default="nova",
                        max_length=10,
                        verbose_name="stav",
                    ),
                ),
                (
                    "price_total",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Podle ceníku v době objednání.",
                        verbose_name="cena celkem (Kč)",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="tým / klub"
                    ),
                ),
                (
                    "sport_name",
                    models.CharField(blank=True, max_length=100, verbose_name="sport"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="kategorie"
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("vstupni", "Vstupní diagnostika"),
                            ("progres", "Kontrola tréninkového progresu"),
                            ("sezona", "Příprava na sezónu"),
                            ("navrat", "Návrat po zranění"),
                            ("jine", "Jiný cíl"),
                        ],
                        default="vstupni",
                        max_length=10,
                        verbose_name="cíl testování",
                    ),
                ),
                (
                    "goal_note",
                    models.TextField(blank=True, verbose_name="cíl – upřesnění"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("rec", "Rekreační"),
                            ("trained", "Trénovaný"),
                            ("national", "Národní úroveň"),
                            ("intl", "Mezinárodní úroveň"),
                        ],
                        default="trained",
                        max_length=20,
                        verbose_name="výkonnostní úroveň",
                    ),
                ),
                (
                    "season_phase",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prep", "Přípravné období"),
                            ("comp", "Závodní období"),
                            ("trans", "Přechodné období"),
                            ("rtp", "Návrat po zranění"),
                        ],
                        max_length=10,
                        verbose_name="tréninkové období",
                    ),
                ),
                (
                    "contact_name_enc",
                    models.TextField(
                        blank=True, verbose_name="kontaktní osoba (šifrovaně)"
                    ),
                ),
                (
                    "email_enc",
                    models.TextField(blank=True, verbose_name="e-mail (šifrovaně)"),
                ),
                (
                    "phone_enc",
                    models.TextField(blank=True, verbose_name="telefon (šifrovaně)"),
                ),
                (
                    "consent_testing",
                    models.BooleanField(
                        default=False,
                        verbose_name="souhlas s testováním a zpracováním údajů",
                    ),
                ),
                (
                    "consent_handover",
                    models.BooleanField(
                        default=False, verbose_name="souhlas s předáním zprávy lékaři"
                    ),
                ),
                (
                    "consent_guardian",
                    models.BooleanField(
                        default=False,
                        verbose_name="souhlas zákonných zástupců nezletilých",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.booking.models._token,
                        editable=False,
                        max_length=40,
                        unique=True,
                        verbose_name="odkaz pro klienta",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="e-mail potvrzen"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="vyřízeno"
                    ),
                ),
                (
                    "decision_note",
                    models.TextField(blank=True, verbose_name="zpráva klientovi"),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vyřídil",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
                (
                    "offers",
                    models.ManyToManyField(
                        related_name="requests",
                        to="booking.offer",
                        verbose_name="objednané testy",
                    ),
                ),
            ],
            options={
                "verbose_name": "objednávka",
                "verbose_name_plural": "objednávky",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name_enc", models.TextField(verbose_name="jméno (šifrovaně)")),
                (
                    "last_name_enc",
                    models.TextField(verbose_name="příjmení (šifrovaně)"),
                ),
                (
                    "birth_date_enc",
                    models.TextField(verbose_name="datum narození (šifrovaně)"),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("F", "Žena"),
                            ("M", "Muž"),
                            ("X", "Jiné / neuvedeno"),
                        ],
                        default="X",
                        max_length=1,
                        verbose_name="pohlaví",
                    ),
                ),
                (
                    "injury_enc",
                    models.TextField(blank=True, verbose_name="zranění (šifrovaně)"),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="booking.bookingrequest",
                        verbose_name="objednávka",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="measurements.testsession",
                        verbose_name="testovací den",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="subjects.subject",
                        verbose_name="sportovec v aplikaci",
                    ),
                ),
            ],
            options={
                "verbose_name": "účastník",
                "verbose_name_plural": "účastníci",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                ("start", models.DateTimeField(verbose_name="začátek")),
                (
                    "duration_min",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="délka (min)"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="laboratoř / místo"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="kapacita (osob)"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="poznámka pro klienta"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="nabízet"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
            ],
            options={
                "verbose_name": "volný termín",
                "verbose_name_plural": "volné termíny",
                "ordering": ["start"],
            },
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="booking.slot",
                verbose_name="termín",
            ),
        ),
    ]
