# Generated by Django 5.1.15 on 2026-09-21 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("measurements", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "report_number",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="číslo zprávy"
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(default=1, verbose_name="verze"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Koncept"),
                            ("released", "Vydáno"),
                            ("superseded", "Nahrazeno novější verzí"),
                        ],
                        default="draft",
                        max_length=12,
                        verbose_name="stav",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Zpráva z funkčního testování",
                        max_length=200,
                        verbose_name="název",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="souhrn")),
                (
                    "custom_note",
                    models.TextField(blank=True, verbose_name="vlastní komentář"),
                ),
                (
                    "disclaimer",
                    models.TextField(
                        default="Uvedená doporučení vycházejí výhradně z výsledků funkčního testování. Jejich zařazení je podmíněno posouzením zdravotního stavu a případných kontraindikací ošetřujícím lékařem.",
                        verbose_name="doložka",
                    ),
                ),
                (
                    "rules_version",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="verze sady pravidel"
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="použitý jazykový model"
                    ),
                ),
                (
                    "input_fingerprint",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="otisk vstupů"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True, upload_to="reports/%Y/%m/", verbose_name="PDF"
                    ),
                ),
                (
                    "data_json",
                    models.FileField(
                        blank=True,
                        upload_to="reports/%Y/%m/",
                        verbose_name="strojově čitelná příloha",
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="vydáno"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="released_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vydal",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="measurements.testsession",
                        verbose_name="testovací den",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="subjects.subject",
                        verbose_name="sportovec",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="reports.report",
                        verbose_name="nahrazuje",
                    ),
                ),
            ],
            options={
                "verbose_name": "zpráva",
                "verbose_name_plural": "zprávy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "recipient",
                    models.CharField(max_length=200, verbose_name="příjemce"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("link", "Zabezpečený odkaz"),
                            ("handover", "Osobní předání"),
                            ("api", "Rozhraní"),
                        ],
                        default="link",
                        max_length=12,
                        verbose_name="kanál",
                    ),
                ),
                ("delivered_at", models.DateTimeField(verbose_name="předáno")),
                (
                    "consent_verified",
                    models.BooleanField(
                        default=False, verbose_name="souhlas s předáním ověřen"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="potvrzeno příjemcem"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="poznámka"
                    ),
                ),
                (
                    "delivered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="předal",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="reports.report",
                        verbose_name="zpráva",
                    ),
                ),
            ],
            options={
                "verbose_name": "předání zprávy",
                "verbose_name_plural": "předání zpráv",
                "ordering": ["-delivered_at"],
            },
        ),
    ]
