# Generated by Django 5.1.15 on 2026-09-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="generation_note",
            field=models.TextField(
                blank=True,
                help_text="Proč se model nepoužil, pokud se nepoužil – např. odmítnutý text.",
                verbose_name="poznámka ke vzniku textu",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="llm_model",
            field=models.CharField(
                blank=True,
                help_text="Název jazykového modelu, nebo „šablona“.",
                max_length=80,
                verbose_name="text sestavil",
            ),
        ),
    ]
