# Generated by Django 5.1.15 on 2026-09-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_report_generation_note_alter_report_llm_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="rendered_html",
            field=models.TextField(
                blank=True,
                help_text="Snímek zprávy pořízený při vydání; vydaná zpráva se už nepřepočítává.",
                verbose_name="podoba při vydání",
            ),
        ),
    ]
