# Generated by Django 5.1.15 on 2026-09-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_snimek_vydane_zpravy"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="note_ai_model",
            field=models.CharField(
                blank=True,
                help_text="Model, který navrhl text komentáře; prázdné = psal jen člověk.",
                max_length=80,
                verbose_name="návrh doporučení připravil",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="note_pending_review",
            field=models.BooleanField(
                default=False,
                help_text="Dokud diagnostik návrh neprojde a neuloží, zprávu nelze vydat.",
                verbose_name="návrh od modelu čeká na kontrolu",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="summary_edited",
            field=models.BooleanField(
                default=False, verbose_name="souhrn upraven diagnostikem"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="summary_generated",
            field=models.TextField(blank=True, verbose_name="souhrn, jak vznikl"),
        ),
    ]
