# Generated by Django 5.1.15 on 2026-10-07 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("reports", "0004_upravy_diagnostika"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="ai_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dobry", "Dobrý – stačily drobnosti"),
                    ("pouzitelny", "Použitelný – musel jsem upravit"),
                    ("prepsano", "Nepoužitelný – přepsal jsem ho"),
                ],
                max_length=10,
                verbose_name="hodnocení textu od AI",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_rating_note",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="co bylo špatně"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="audience",
            field=models.CharField(
                choices=[
                    ("sportovec", "Sportovec"),
                    ("trener", "Trenér"),
                    ("lekar", "Lékař / fyzioterapeut"),
                ],
                default="trener",
                max_length=10,
                verbose_name="pro koho",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="in_test_set",
            field=models.BooleanField(
                default=False,
                help_text="Na zprávách ve zkušební sadě se porovnávají modely a pokyny.",
                verbose_name="ve zkušební sadě",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="is_example",
            field=models.BooleanField(
                default=False,
                help_text="Model dostane souhrn této zprávy jako ukázku stylu u podobných zpráv.",
                verbose_name="vzorová zpráva",
            ),
        ),
        migrations.CreateModel(
            name="ModelTrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                ("model", models.CharField(max_length=120, verbose_name="model")),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("sportovec", "Sportovec"),
                            ("trener", "Trenér"),
                            ("lekar", "Lékař / fyzioterapeut"),
                        ],
                        max_length=10,
                        verbose_name="pro koho",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="text")),
                ("seconds", models.FloatField(default=0, verbose_name="trvání (s)")),
                (
                    "problems",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="čísla bez opory v datech",
                    ),
                ),
                (
                    "error",
                    models.CharField(blank=True, max_length=300, verbose_name="chyba"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="spustil",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_trials",
                        to="reports.report",
                        verbose_name="zpráva",
                    ),
                ),
            ],
            options={
                "verbose_name": "zkušební text modelu",
                "verbose_name_plural": "zkušební texty modelů",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("sportovec", "Sportovec"),
                            ("trener", "Trenér"),
                            ("lekar", "Lékař / fyzioterapeut"),
                        ],
                        max_length=10,
                        verbose_name="pro koho",
                    ),
                ),
                ("instructions", models.TextField(verbose_name="pokyny pro model")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="upravil",
                    ),
                ),
            ],
            options={
                "verbose_name": "styl zprávy",
                "verbose_name_plural": "styly zpráv",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "audience"), name="uniq_report_style"
                    )
                ],
            },
        ),
    ]
