# Generated by Django 5.1.15 on 2026-10-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_varianty_a_kvalita_ai"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Přesně jak ho uvádí LM Studio / Ollama, např. meta/muse-glimmer.",
                        max_length=120,
                        unique=True,
                        verbose_name="název na serveru",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="název v aplikaci"
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="Velký model na počítači bez grafické karty potřebuje víc času.",
                        verbose_name="čekat nejvýš (s)",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="výchozí"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="nabízet"),
                ),
            ],
            options={
                "verbose_name": "jazykový model",
                "verbose_name_plural": "jazykové modely",
                "ordering": ["-is_default", "label", "name"],
            },
        ),
        migrations.AddField(
            model_name="report",
            name="writing",
            field=models.CharField(
                blank=True,
                choices=[("", "hotovo"), ("pise", "model píše souhrn")],
                default="",
                max_length=8,
                verbose_name="psaní souhrnu",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="writing_model",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="píše model"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="writing_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="psaní začalo"
            ),
        ),
    ]
