# Generated by Django 5.1.15 on 2026-10-08 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("reports", "0006_modely_a_psani_na_pozadi"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reportstyle",
            name="uniq_report_style",
        ),
        migrations.AddField(
            model_name="report",
            name="literature",
            field=models.JSONField(
                blank=True, null=True, verbose_name="literatura ke zprávě"
            ),
        ),
        migrations.AddField(
            model_name="reportstyle",
            name="kind",
            field=models.CharField(
                choices=[
                    ("souhrn", "Souhrn zprávy"),
                    ("doporuceni", "Návrh doporučení"),
                ],
                default="souhrn",
                max_length=12,
                verbose_name="k čemu",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportstyle",
            constraint=models.UniqueConstraint(
                fields=("organization", "audience", "kind"),
                name="uniq_report_style_kind",
            ),
        ),
    ]
