# Generated by Django 5.1.15 on 2026-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetricDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                ("code", models.SlugField(max_length=64, verbose_name="kód")),
                ("name", models.CharField(max_length=200, verbose_name="název")),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("force_plate", "Force plate"),
                            ("dynamometry", "Dynamometrie"),
                            ("spiro", "Spiroergometrie"),
                            ("body_comp", "Složení těla"),
                            ("field", "Terénní test"),
                            ("other", "Jiné"),
                        ],
                        max_length=20,
                        verbose_name="rodina testů",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="jednotka"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("higher", "Vyšší je lepší"),
                            ("lower", "Nižší je lepší"),
                            ("optimal", "Optimum v pásmu"),
                            ("neutral", "Neutrální (jen sledovaná)"),
                        ],
                        default="higher",
                        max_length=10,
                        verbose_name="žádoucí směr",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Text do legendy zprávy.",
                        verbose_name="popis",
                    ),
                ),
                (
                    "typical_error",
                    models.FloatField(
                        blank=True, null=True, verbose_name="typická chyba měření"
                    ),
                ),
                (
                    "mdc",
                    models.FloatField(
                        blank=True,
                        help_text="Nejmenší detekovatelná změna (v jednotkách metriky).",
                        null=True,
                        verbose_name="MDC",
                    ),
                ),
                (
                    "swc",
                    models.FloatField(
                        blank=True,
                        help_text="Nejmenší prakticky významná změna.",
                        null=True,
                        verbose_name="SWC",
                    ),
                ),
                (
                    "plausible_min",
                    models.FloatField(
                        blank=True, null=True, verbose_name="věrohodné minimum"
                    ),
                ),
                (
                    "plausible_max",
                    models.FloatField(
                        blank=True, null=True, verbose_name="věrohodné maximum"
                    ),
                ),
                (
                    "decimals",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="desetinná místa"
                    ),
                ),
                (
                    "loinc_code",
                    models.CharField(
                        blank=True,
                        help_text="Jen tam, kde standard existuje (složení těla, laboratoř).",
                        max_length=20,
                        verbose_name="kód LOINC",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="aktivní"),
                ),
            ],
            options={
                "verbose_name": "metrika",
                "verbose_name_plural": "metriky",
                "ordering": ["family", "name"],
            },
        ),
        migrations.CreateModel(
            name="Norm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Žena"), ("M", "Muž")],
                        help_text="Prázdné = obě pohlaví.",
                        max_length=1,
                        verbose_name="pohlaví",
                    ),
                ),
                (
                    "age_min",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="věk od"
                    ),
                ),
                (
                    "age_max",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="věk do"
                    ),
                ),
                (
                    "level",
                    models.CharField(blank=True, max_length=20, verbose_name="úroveň"),
                ),
                (
                    "side",
                    models.CharField(blank=True, max_length=10, verbose_name="strana"),
                ),
                (
                    "mode",
                    models.CharField(blank=True, max_length=20, verbose_name="režim"),
                ),
                (
                    "speed",
                    models.FloatField(blank=True, null=True, verbose_name="rychlost"),
                ),
                (
                    "mean",
                    models.FloatField(blank=True, null=True, verbose_name="průměr"),
                ),
                (
                    "sd",
                    models.FloatField(
                        blank=True, null=True, verbose_name="směrodatná odchylka"
                    ),
                ),
                (
                    "percentiles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Např. {"10": 21.4, "50": 28.9, "90": 35.2}',
                        verbose_name="percentily",
                    ),
                ),
                (
                    "source_citation",
                    models.CharField(max_length=500, verbose_name="citace zdroje"),
                ),
                (
                    "source_doi",
                    models.CharField(blank=True, max_length=120, verbose_name="DOI"),
                ),
                (
                    "sample_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="velikost vzorku"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="poznámka")),
            ],
            options={
                "verbose_name": "norma",
                "verbose_name_plural": "normy",
                "ordering": ["metric", "sport", "sex"],
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                ("code", models.SlugField(max_length=64, verbose_name="kód")),
                ("name", models.CharField(max_length=200, verbose_name="název")),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("force_plate", "Force plate"),
                            ("dynamometry", "Dynamometrie"),
                            ("spiro", "Spiroergometrie"),
                            ("body_comp", "Složení těla"),
                            ("field", "Terénní test"),
                            ("other", "Jiné"),
                        ],
                        max_length=20,
                        verbose_name="rodina testů",
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(default=1, verbose_name="verze"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="popis procedury"),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="přístroj"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="aktivní"),
                ),
            ],
            options={
                "verbose_name": "protokol",
                "verbose_name_plural": "protokoly",
                "ordering": ["family", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="pořadí"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Zobrazuje se na kartě sportovce a v souhrnu zprávy.",
                        verbose_name="klíčová metrika",
                    ),
                ),
            ],
            options={
                "verbose_name": "metrika protokolu",
                "verbose_name_plural": "metriky protokolu",
                "ordering": ["order"],
            },
        ),
    ]
