# Generated by Django 5.1.15 on 2026-09-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricdef",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Prázdné = sdílený záznam platný pro všechna pracoviště.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.organization",
                verbose_name="organizace",
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="metric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="norms",
                to="catalog.metricdef",
                verbose_name="metrika",
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Prázdné = sdílený záznam platný pro všechna pracoviště.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.organization",
                verbose_name="organizace",
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                help_text="Prázdné = platí napříč sporty.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subjects.sport",
                verbose_name="sport",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Prázdné = sdílený záznam platný pro všechna pracoviště.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.organization",
                verbose_name="organizace",
            ),
        ),
        migrations.AddField(
            model_name="protocolmetric",
            name="metric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="protocol_metrics",
                to="catalog.metricdef",
                verbose_name="metrika",
            ),
        ),
        migrations.AddField(
            model_name="protocolmetric",
            name="protocol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocol_metrics",
                to="catalog.protocol",
                verbose_name="protokol",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricdef",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="uniq_metric_code_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="norm",
            index=models.Index(
                fields=["metric", "sport", "sex"], name="catalog_nor_metric__f1f1d3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="protocol",
            constraint=models.UniqueConstraint(
                fields=("organization", "code", "version"),
                name="uniq_protocol_code_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="protocolmetric",
            constraint=models.UniqueConstraint(
                fields=("protocol", "metric"), name="uniq_protocol_metric"
            ),
        ),
    ]
