# Generated by Django 5.1.15 on 2026-09-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="default_trials",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Kolik opakování se standardně měří. Zadávací formulář podle toho udělá sloupce.",
                verbose_name="počet pokusů",
            ),
        ),
        migrations.AddField(
            model_name="protocolmetric",
            name="modes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Např. ["con", "ecc"]. Prázdné = bez rozlišení.',
                verbose_name="režimy",
            ),
        ),
        migrations.AddField(
            model_name="protocolmetric",
            name="segments",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Např. ["paze", "noha", "trup"].',
                verbose_name="segmenty",
            ),
        ),
        migrations.AddField(
            model_name="protocolmetric",
            name="sides",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Např. ["L", "R"] nebo ["B"]. Prázdné = bez rozlišení.',
                verbose_name="strany",
            ),
        ),
        migrations.AddField(
            model_name="protocolmetric",
            name="speeds",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Např. [210, 300]. Prázdné = bez rozlišení.",
                verbose_name="rychlosti",
            ),
        ),
    ]
