# Generated by Django 5.1.15 on 2026-09-25 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_protocol_default_trials_protocolmetric_modes_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "device",
                    models.CharField(
                        choices=[
                            ("vald_forcedecks", "VALD ForceDecks"),
                            ("vald_humantrak", "VALD HumanTrak"),
                        ],
                        max_length=32,
                        verbose_name="přístroj",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        help_text="Přesně jak ho píše export, např. „Countermovement Jump“.",
                        max_length=120,
                        verbose_name="typ testu v exportu",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="aktivní"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Prázdné = sdílený záznam platný pro všechna pracoviště.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_profiles",
                        to="catalog.protocol",
                        verbose_name="protokol",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil importu",
                "verbose_name_plural": "profily importu",
                "ordering": ["device", "test_type"],
            },
        ),
        migrations.CreateModel(
            name="ImportColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "column",
                    models.CharField(max_length=200, verbose_name="sloupec v exportu"),
                ),
                (
                    "with_sides",
                    models.BooleanField(
                        default=True,
                        help_text="Importovat i varianty „(Left)“ a „(Right)“, pokud je export má. Vypněte u časů a poměrů, kde rozdíl stran nic neříká.",
                        verbose_name="i levá a pravá strana",
                    ),
                ),
                (
                    "factor",
                    models.FloatField(
                        default=1.0,
                        help_text="Převod hodnoty, např. −1 pro obrácení znaménka nebo 0,001 pro ms → s.",
                        verbose_name="násobek",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_columns",
                        to="catalog.metricdef",
                        verbose_name="metrika",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="catalog.importprofile",
                        verbose_name="profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "importovaný sloupec",
                "verbose_name_plural": "importované sloupce",
                "ordering": ["pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="importprofile",
            constraint=models.UniqueConstraint(
                fields=("organization", "device", "test_type"),
                name="uniq_import_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="importcolumn",
            constraint=models.UniqueConstraint(
                fields=("profile", "column"), name="uniq_import_column"
            ),
        ),
    ]
