# Generated by Django 5.1.15 on 2026-09-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_profily_importu"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricdef",
            name="ods_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vysledek", "Výsledek (co sportovec dokázal)"),
                    ("pricina", "Příčina (co výsledek pohání)"),
                    ("strategie", "Strategie (jak pohyb provedl)"),
                ],
                max_length=10,
                verbose_name="role v ODS",
            ),
        ),
        migrations.AddField(
            model_name="metricdef",
            name="trial_cv_limit",
            field=models.FloatField(
                blank=True,
                help_text="Když se pokusy téhož dne liší víc (variační koeficient), aplikace upozorní, že je vhodné pokus zopakovat. Prázdné = nekontroluje se.",
                null=True,
                verbose_name="max. rozptyl pokusů (CV %)",
            ),
        ),
    ]
