# Generated by Django 5.1.15 on 2026-09-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_ods_a_rozptyl_pokusu"),
        ("core", "0001_initial"),
        ("subjects", "0004_kategorie_sportovce"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestBattery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Např. „dorost“. Prázdné = platí pro celý sport.",
                        max_length=60,
                        verbose_name="kategorie",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="název"),
                ),
                ("note", models.TextField(blank=True, verbose_name="poznámka")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batteries",
                        to="subjects.sport",
                        verbose_name="sport",
                    ),
                ),
            ],
            options={
                "verbose_name": "baterie testů",
                "verbose_name_plural": "baterie testů",
                "ordering": ["sport__name", "category"],
            },
        ),
        migrations.CreateModel(
            name="BatteryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="pořadí"),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="battery_items",
                        to="catalog.protocol",
                        verbose_name="protokol",
                    ),
                ),
                (
                    "battery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.testbattery",
                        verbose_name="baterie",
                    ),
                ),
            ],
            options={
                "verbose_name": "test v baterii",
                "verbose_name_plural": "testy v baterii",
                "ordering": ["order", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("battery", "protocol"), name="uniq_battery_protocol"
                    )
                ],
            },
        ),
    ]
