# Generated by Django 5.1.15 on 2026-09-26 17:04

import django.db.models.deletion
from django.db import migrations, models


def vychozi_nastaveni(apps, schema_editor):
    """
    Jednorázově pro existující databáze: RPE po zátěžových testech a nejlepší
    pokus u stisku a podání. Pozdější úpravy v administraci už nic nepřepíše.
    """
    Protocol = apps.get_model("catalog", "Protocol")
    MetricDef = apps.get_model("catalog", "MetricDef")
    Protocol.objects.filter(organization=None, code__in=["wingate", "spiro_ramp"]).update(
        rpe_after=True)
    MetricDef.objects.filter(organization=None, code__in=["grip_strength", "serve_speed"]).update(
        trial_rule="nejlepsi")


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_baterie_testu"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricdef",
            name="trial_rule",
            field=models.CharField(
                choices=[
                    ("prumer", "Průměr platných pokusů"),
                    ("nejlepsi", "Nejlepší pokus"),
                    ("posledni", "Poslední pokus"),
                ],
                default="prumer",
                help_text="Nejlepší = nejvyšší, nebo nejnižší hodnota podle žádoucího směru (u času sprintu nejkratší). U ukazatelů bez směru se průměruje.",
                max_length=10,
                verbose_name="hodnota dne z pokusů",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="rest_seconds",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Při zadávání se nabídne odpočet pauzy. Prázdné = bez odpočtu.",
                null=True,
                verbose_name="pauza mezi pokusy (s)",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="rpe_after",
            field=models.BooleanField(
                default=False,
                help_text="Při zadávání se nabídne škála RPE (subjektivně vnímané úsilí). Hodí se u zátěžových testů – Wingate, spiroergometrie, terénní běhy.",
                verbose_name="po testu zaznamenat RPE",
            ),
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                ("code", models.SlugField(max_length=64, verbose_name="kód")),
                ("name", models.CharField(max_length=200, verbose_name="název")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="pokyn pro sportovce"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="aktivní"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Prázdné = sdílený záznam platný pro všechna pracoviště.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
            ],
            options={
                "verbose_name": "dotazník",
                "verbose_name_plural": "dotazníky",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, verbose_name="kód")),
                ("text", models.CharField(max_length=300, verbose_name="otázka")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="pořadí"),
                ),
                (
                    "scale_min",
                    models.SmallIntegerField(default=0, verbose_name="škála od"),
                ),
                (
                    "scale_max",
                    models.SmallIntegerField(default=10, verbose_name="škála do"),
                ),
                (
                    "anchors",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Např. {"0": "klid", "10": "maximální úsilí"}. Body bez popisku se ukážou jen číslem.',
                        verbose_name="popisky bodů škály",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="catalog.questionnaire",
                        verbose_name="dotazník",
                    ),
                ),
            ],
            options={
                "verbose_name": "otázka",
                "verbose_name_plural": "otázky",
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="questionnaire",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="uniq_questionnaire_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("questionnaire", "code"), name="uniq_question_code"
            ),
        ),
        migrations.RunPython(vychozi_nastaveni, migrations.RunPython.noop),
    ]
