# Generated by Django 5.1.15 on 2026-10-01 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_terenni_testy_a_dotazniky"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importcolumn",
            name="segment",
            field=models.CharField(
                blank=True,
                help_text="Např. paze, noha, trup.",
                max_length=32,
                verbose_name="část těla",
            ),
        ),
        migrations.AddField(
            model_name="importcolumn",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("B", "celkem / obě"), ("L", "levá"), ("R", "pravá")],
                max_length=1,
                verbose_name="strana",
            ),
        ),
        migrations.AlterField(
            model_name="importprofile",
            name="device",
            field=models.CharField(max_length=64, verbose_name="přístroj"),
        ),
        migrations.AlterField(
            model_name="importprofile",
            name="test_type",
            field=models.CharField(
                blank=True,
                help_text="Přesně jak ho píše export, např. „Countermovement Jump“. U přístroje přidaného průvodcem prázdné.",
                max_length=120,
                verbose_name="typ testu v exportu",
            ),
        ),
        migrations.CreateModel(
            name="DeviceFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="název přístroje"),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Vznikne z názvu a už se nemění – podle něj se přístroj pozná i po přenosu katalogu.",
                        max_length=40,
                        verbose_name="kód",
                    ),
                ),
                (
                    "header_row",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="řádek s názvy sloupců"
                    ),
                ),
                (
                    "columns_seen",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Názvy sloupců z ukázkového souboru (bez dat).",
                        verbose_name="sloupce v souboru",
                    ),
                ),
                (
                    "name_column",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="jméno a příjmení"
                    ),
                ),
                (
                    "first_name_column",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="křestní jméno"
                    ),
                ),
                (
                    "last_name_column",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="příjmení"
                    ),
                ),
                (
                    "id_column",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ID v přístroji"
                    ),
                ),
                (
                    "birth_column",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="datum narození"
                    ),
                ),
                (
                    "sex_column",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="pohlaví"
                    ),
                ),
                (
                    "date_column",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="datum měření"
                    ),
                ),
                (
                    "time_column",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="čas měření"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="připravený k importu"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Prázdné = sdílený záznam platný pro všechna pracoviště.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_formats",
                        to="catalog.protocol",
                        verbose_name="test",
                    ),
                ),
            ],
            options={
                "verbose_name": "přístroj (vlastní formát)",
                "verbose_name_plural": "přístroje (vlastní formát)",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "code"), name="uniq_device_format"
                    )
                ],
            },
        ),
    ]
