# Generated by Django 5.1.15 on 2026-09-21 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("core", "0001_initial"),
        ("measurements", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                ("adapter", models.CharField(max_length=64, verbose_name="adaptér")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Nahráno"),
                            ("parsed", "Zpracováno, čeká na kontrolu"),
                            ("committed", "Uloženo"),
                            ("failed", "Chyba"),
                            ("cancelled", "Zrušeno"),
                        ],
                        default="uploaded",
                        max_length=12,
                        verbose_name="stav",
                    ),
                ),
                (
                    "summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="souhrn kontroly"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="chyba")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="catalog.protocol",
                        verbose_name="protokol",
                    ),
                ),
                (
                    "raw_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="measurements.rawfile",
                        verbose_name="zdrojový soubor",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="nahrál",
                    ),
                ),
            ],
            options={
                "verbose_name": "import",
                "verbose_name_plural": "importy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StagedMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(default=0, verbose_name="řádek zdroje"),
                ),
                (
                    "subject_hint",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="identifikace ze souboru",
                    ),
                ),
                (
                    "metric_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="kód metriky"
                    ),
                ),
                (
                    "trial_number",
                    models.PositiveSmallIntegerField(default=1, verbose_name="pokus"),
                ),
                (
                    "side",
                    models.CharField(blank=True, max_length=1, verbose_name="strana"),
                ),
                (
                    "mode",
                    models.CharField(blank=True, max_length=3, verbose_name="režim"),
                ),
                (
                    "speed",
                    models.FloatField(blank=True, null=True, verbose_name="rychlost"),
                ),
                (
                    "segment",
                    models.CharField(blank=True, max_length=32, verbose_name="segment"),
                ),
                (
                    "value",
                    models.FloatField(blank=True, null=True, verbose_name="hodnota"),
                ),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("ok", "V pořádku"),
                            ("unknown_subject", "Neznámý sportovec"),
                            ("unknown_metric", "Neznámá metrika"),
                            ("range", "Mimo věrohodný rozsah"),
                            ("duplicate", "Duplicita"),
                        ],
                        default="ok",
                        max_length=20,
                        verbose_name="příznak",
                    ),
                ),
                (
                    "message",
                    models.CharField(blank=True, max_length=255, verbose_name="zpráva"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staged",
                        to="ingest.importbatch",
                        verbose_name="import",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.metricdef",
                        verbose_name="metrika",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subjects.subject",
                        verbose_name="sportovec",
                    ),
                ),
            ],
            options={
                "verbose_name": "hodnota ke kontrole",
                "verbose_name_plural": "hodnoty ke kontrole",
                "ordering": ["row_number"],
            },
        ),
    ]
