# Generated by Django 5.1.15 on 2026-09-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedmeasurement",
            name="protocol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.protocol",
                verbose_name="protokol",
            ),
        ),
        migrations.AddField(
            model_name="stagedmeasurement",
            name="protocol_code",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="kód protokolu"
            ),
        ),
        migrations.AddField(
            model_name="stagedmeasurement",
            name="session_date",
            field=models.DateField(blank=True, null=True, verbose_name="datum měření"),
        ),
        migrations.AddField(
            model_name="stagedmeasurement",
            name="subject_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash identifikace ze zdroje – páruje opakované importy téže osoby bez ukládání jména.",
                max_length=64,
                verbose_name="klíč sportovce",
            ),
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="protocol",
            field=models.ForeignKey(
                blank=True,
                help_text="Použije se u řádků, které protokol neurčují samy.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_batches",
                to="catalog.protocol",
                verbose_name="výchozí protokol",
            ),
        ),
        migrations.AlterField(
            model_name="stagedmeasurement",
            name="subject_hint",
            field=models.CharField(
                blank=True,
                help_text="Jen pro náhled. Po uložení se maže.",
                max_length=200,
                verbose_name="identifikace ze souboru",
            ),
        ),
    ]
