# Generated by Django 5.1.15 on 2026-09-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0002_stagedmeasurement_protocol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedmeasurement",
            name="run_key",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="identifikace testu ve zdroji"
            ),
        ),
        migrations.AddField(
            model_name="stagedmeasurement",
            name="run_started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="čas testu"),
        ),
        migrations.AlterField(
            model_name="stagedmeasurement",
            name="flag",
            field=models.CharField(
                choices=[
                    ("ok", "V pořádku"),
                    ("unknown_subject", "Neznámý sportovec"),
                    ("unknown_metric", "Neznámá metrika"),
                    ("range", "Mimo věrohodný rozsah"),
                    ("duplicate", "Test už je v aplikaci"),
                ],
                default="ok",
                max_length=20,
                verbose_name="příznak",
            ),
        ),
    ]
