# Generated by Django 5.1.15 on 2026-09-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("evidence", "0001_initial"),
        ("measurements", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                ("code", models.SlugField(max_length=64, verbose_name="kód")),
                ("name", models.CharField(max_length=200, verbose_name="název")),
                (
                    "version",
                    models.PositiveSmallIntegerField(default=1, verbose_name="verze"),
                ),
                ("condition", models.JSONField(default=dict, verbose_name="podmínka")),
                (
                    "contraindication",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Podmínka, která pravidlo potlačí.",
                        verbose_name="kontraindikace",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informativní"),
                            ("low", "Nízká"),
                            ("medium", "Střední"),
                            ("high", "Vysoká"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="závažnost",
                    ),
                ),
                (
                    "finding_template",
                    models.TextField(
                        help_text="Šablona, např. 'Poměr IR/ER {value:.2f} je pod doporučenou hodnotou {threshold:.2f}.'",
                        verbose_name="text nálezu",
                    ),
                ),
                (
                    "recommendation_template",
                    models.TextField(blank=True, verbose_name="text doporučení"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="aktivní"),
                ),
                (
                    "applies_to_sport",
                    models.ForeignKey(
                        blank=True,
                        help_text="Prázdné = napříč sporty.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.sport",
                        verbose_name="platí pro sport",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Prázdné = sdílený záznam platný pro všechna pracoviště.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                        verbose_name="organizace",
                    ),
                ),
            ],
            options={
                "verbose_name": "pravidlo",
                "verbose_name_plural": "pravidla",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="změněno"),
                ),
                (
                    "rule_version",
                    models.PositiveSmallIntegerField(verbose_name="verze pravidla"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informativní"),
                            ("low", "Nízká"),
                            ("medium", "Střední"),
                            ("high", "Vysoká"),
                        ],
                        max_length=10,
                        verbose_name="závažnost",
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        default=dict,
                        help_text="Čísla, která pravidlo použilo. Text zprávy nesmí obsahovat žádná jiná.",
                        verbose_name="hodnoty",
                    ),
                ),
                ("text", models.TextField(verbose_name="text nálezu")),
                (
                    "suppressed",
                    models.BooleanField(
                        default=False, verbose_name="potlačeno kontraindikací"
                    ),
                ),
                (
                    "suppressed_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="důvod potlačení"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="measurements.testsession",
                        verbose_name="testovací den",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="rules.rule",
                        verbose_name="pravidlo",
                    ),
                ),
            ],
            options={
                "verbose_name": "nález",
                "verbose_name_plural": "nálezy",
                "ordering": ["-severity", "rule__code"],
            },
        ),
        migrations.CreateModel(
            name="RuleArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relevance_note",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="proč je relevantní"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rule_articles",
                        to="evidence.article",
                        verbose_name="článek",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_articles",
                        to="rules.rule",
                        verbose_name="pravidlo",
                    ),
                ),
            ],
            options={
                "verbose_name": "evidence pravidla",
                "verbose_name_plural": "evidence pravidel",
            },
        ),
        migrations.AddConstraint(
            model_name="rule",
            constraint=models.UniqueConstraint(
                fields=("organization", "code", "version"),
                name="uniq_rule_code_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulearticle",
            constraint=models.UniqueConstraint(
                fields=("rule", "article"), name="uniq_rule_article"
            ),
        ),
    ]
